### ISSUE TITLE
Array backend additional TODO list

### ISSUE THREAD

**Issue by jangko** [status-im/nim-stint#130]
- [ ] fix compiletime test_uint_muldiv 
- [ ] fix compiletime test_uint_modular_arithmetic
- [ ] add native signed integer  operand to addsub operations
- [ ] add native signed integer operand to muldiv operations
